### ISSUE TITLE
installation and customization

### ISSUE THREAD

**Issue by PrinceOjha0** [andrea-patricelli/syncope#37]
please explain how to use it and installation and customization there is no video on youtube for installing and for integration it is very hard to understand your documentation and explaining more briefly with image else you i will do all the thing for you

**Comment by andrea-patricelli** [comment]
Hi @PrinceOjha0 ! Nice to know about you interest in Apache Syncope. 
This repository is quite outdated and was meant only for training purposes. Please follow documentation at https://syncope.apache.org/docs/3.0/getting-started.html and https://syncope.apache.org/docs/3.0/reference-guide.html to know about how to start working with Syncope and subscribe to the user mailing list https://syncope.apache.org/mailing-lists for any question.

Best regards
